[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/ar/*"
  to = "/ar/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/en/index.html"
  status = 200
